GOOGLE_API_KEY = "AIzaSyBXdf7KxATDxLDbPZWRhqgZZHgq78_dYDY"


# --- ArangoDB Credentials ---
# Use the "APPLICATION ENDPOINT" from your screenshot
ARANGO_HOST = "https://f35a5e8cb378.arangodb.cloud:8529"

# The database we will create/use inside the deployment
ARANGO_DATABASE = "llm_graph"

# The default superuser for ArangoDB
ARANGO_USER = "root"

# Get this by clicking the "eye" icon in your screenshot
ARANGO_PASSWORD = "WkXOGo6mpWF6EYMNEHoJ"

GOOGLE_CSE_ID = "44c6f5678e40a4b20"
