GOOGLE_API_KEY = "AIzaSyBXdf7KxATDxLDbPZWRhqgZZHgq78_dYDY"


GOOGLE_CSE_ID = "44c6f5678e40a4b20"


NEO4J_URI = "neo4j+s://0508fa6e.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "bjauiIAEV9NY0nELhcfMlTjYU2hs75Sqh_qw9Uaki94"

